// apps/calendar/src/components/SearchForm.vue
<template>
  <form id="search" @submit.prevent="submitSearch()">
    <div class="row">
      <div class="col-12 my-2">
        <input-date
          :id="'start-date'"
          :name="'start-date'"
          :value="dateRange.start"
          label="Debut"
          @input-date="updateStartDate"
        >
        </input-date>
      </div>
      <div class="col-12 my-2">
        <input-date
          :id="'end-date'"
          :name="'end-date'"
          :value="dateRange.end"
          label="Fin"
          @input-date="updateEndDate"
        >
        </input-date>
      </div>
    </div>
    <div class="row">
      <div class="col-12 my-2">
        <label for="departement"> Département </label>
        <select
          id="departement"
          v-model="dpt"
          name="departement"
          class="form-control"
        >
          <option
            v-for="option in options"
            :key="option.value"
            :value="option.value"
          >
            {{ option.text }}
          </option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="col-12 my-2">
        <div class="mx-auto">
          <button
            id="search_button"
            type="submit"
            class="btn btn-secondary shadow m-2 rounded-pill"
          >
            <i class="fas fa-search"></i> Rechercher
          </button>
          <button
            href="#calendar"
            class="btn btn-outline-dark rounded-pill shadow m-2"
            @click="deleteSearch"
          >
            <i class="far fa-trash-alt"></i> Réinitialiser
          </button>
        </div>
      </div>
    </div>
  </form>
</template>

<script lang="js">
import { ref } from 'vue';
import { cloneDeep } from 'lodash';
import InputDate from './InputDate.vue';
import departementslist from '../constants/departementslist';

const dateNow = new Date(Date.now());
const defaultQuery = {
  startDate: dateNow,
  endDate: new Date(
    dateNow.getFullYear() + 1,
    dateNow.getMonth(),
    dateNow.getDate(),
  ),
  dpt: 'all',
};

export default {
  name: 'SearchForm',
  components: {
    InputDate,
  },
  emits: ['submit-search-form', 'cancel-search-form'],
  setup(props, ctx) {
    const { emit } = ctx;

    const dateRange = ref({
      start: cloneDeep(defaultQuery.startDate),
      end: cloneDeep(defaultQuery.endDate),
    });

    const options = departementslist;

    const dpt = ref(defaultQuery.dpt);

    const submitSearch = () =>
      emit('submit-search-form', {
        dpt: dpt.value,
        startDate: dateRange.value.start,
        endDate: dateRange.value.end,
      });

    const deleteSearch = () => {
      dateRange.value.start = cloneDeep(defaultQuery.startDate);
      dateRange.value.end = cloneDeep(defaultQuery.endDate);
      dpt.value = cloneDeep(defaultQuery.dpt);
      emit('cancel-search-form', { cancel: true });
    };

    const updateStartDate = (val) => {
      dateRange.value.start = val;
    };

    const updateEndDate = (val) => {
      dateRange.value.end = val;
    };

    return {
      dateRange,
      options,
      dpt,
      submitSearch,
      deleteSearch,
      updateStartDate,
      updateEndDate,
    };
  },
};
</script>

// apps/calendar/components/src/components/search-form/search-form.tsx
import { Component, Event, EventEmitter, State, h } from '@stencil/core';
import { cloneDeep } from '../../utils/utils';
import departementslist from '../../constants/departementslist';

const dateNow = new Date(Date.now());
const defaultQuery = {
  startDate: dateNow,
  endDate: new Date(dateNow.getFullYear() + 1, dateNow.getMonth(), dateNow.getDate()),
  dpt: 'all',
};

@Component({
  tag: 'search-form',
  styleUrl: 'search-form.css',
  shadow: true,
})
export class SearchForm {
  @State() dateRange = {
    start: cloneDeep(defaultQuery.startDate),
    end: cloneDeep(defaultQuery.endDate),
  };

  @State() options: { text: string; value: string }[] = departementslist;

  @State() dpt = defaultQuery.dpt;

  @Event({ eventName: 'search-form-launched' }) searchFormLaunched: EventEmitter<{
    dpt: string;
    startDate: string;
    endDate: string;
  }>;
  @Event({ eventName: 'search-form-canceled' }) searchFormCanceled: EventEmitter<{ cancel: boolean }>;

  private submitSearch = (event: SubmitEvent) => {
    event.preventDefault();
    event.stopPropagation();
    this.searchFormLaunched.emit({
      dpt: this.dpt,
      startDate: this.dateRange.start,
      endDate: this.dateRange.end,
    });
  };
  private deleteSearch = () => {
    this.dateRange.start = cloneDeep(defaultQuery.startDate);
    this.dateRange.end = cloneDeep(defaultQuery.endDate);
    this.dpt = cloneDeep(defaultQuery.dpt);
    this.searchFormCanceled.emit({ cancel: true });
  };

  private updateStartDate = (event: CustomEvent) => {
    this.dateRange.start = event.detail;
  };

  private updateEndDate = (event: CustomEvent) => {
    this.dateRange.end = event.detail;
  };

  private handleDepartement = (event: InputEvent & { target: HTMLSelectElement }) => {
    this.dpt = event.target.value;
  };

  render() {
    return (
      <form id="search" onSubmit={this.submitSearch}>
        <div class="my-2">
          <input-date id={'start-date'} name={'start-date'} value={this.dateRange.start} label="Debut" onInput-date={this.updateStartDate}></input-date>
        </div>
        <div class="my-2">
          <input-date id={'end-date'} name={'end-date'} value={this.dateRange.end} label="Fin" onInput-date={this.updateEndDate}></input-date>
        </div>
        <label htmlFor="departement">Département</label>
        <select id="departement" name="departement" onInput={this.handleDepartement}>
          {this.options.map(option => (
            <option key={option.value} value={option.value}>
              {option.text}
            </option>
          ))}
        </select>
        <div>
          <button type="submit">
            <i class="fas fa-search"></i> Rechercher
          </button>
          <button onClick={this.deleteSearch}>
            <span class="far fa-trash-alt"></span> Réinitialiser
          </button>
        </div>
      </form>
    );
  }
}
